/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

description = 'The spring config module of dubbo project'

dependencies {
    api project(':dubbo-config:dubbo-config-api')
    testImplementation project(':dubbo-metrics:dubbo-metrics-prometheus')
    implementation "org.springframework:spring-beans"
    implementation "org.springframework:spring-web"
    implementation "org.springframework:spring-context"
    compileOnly "javax.servlet:javax.servlet-api"
    // Add javax.annotation support (required for Java 9+)
    compileOnly "javax.annotation:javax.annotation-api:${javaxAnnotationApiVersion}"
    testImplementation "org.aspectj:aspectjweaver:${aspectjweaverVersion}"
    testImplementation project(':dubbo-rpc:dubbo-rpc-dubbo')
    testImplementation project(':dubbo-rpc:dubbo-rpc-triple')
    testImplementation project(':dubbo-rpc:dubbo-rpc-injvm')
    testImplementation project(':dubbo-remoting:dubbo-remoting-netty4')
    testImplementation project(':dubbo-serialization:dubbo-serialization-hessian2')
    testImplementation project(':dubbo-serialization:dubbo-serialization-fastjson2')
    testImplementation "javax.validation:validation-api"
    testImplementation "org.hibernate:hibernate-validator"
    testImplementation "org.glassfish:javax.el"
    testImplementation "org.springframework:spring-tx"
    testImplementation "org.springframework:spring-test:${springVersion}"
    testImplementation "org.apache.tomcat.embed:tomcat-embed-core"
    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootStarterTestVersion}"
    testImplementation "org.apache.logging.log4j:log4j-slf4j-impl"
    testImplementation project(':dubbo-registry:dubbo-registry-zookeeper')
    testImplementation project(':dubbo-metadata:dubbo-metadata-report-zookeeper')
    testImplementation project(':dubbo-remoting:dubbo-remoting-zookeeper-curator5')
    testImplementation "org.apache.curator:curator-recipes"
    testImplementation "org.apache.curator:curator-x-discovery"
    testImplementation "org.apache.zookeeper:zookeeper"
    testImplementation project(':dubbo-registry:dubbo-registry-nacos')
    testImplementation project(':dubbo-configcenter:dubbo-configcenter-nacos')
    testImplementation "com.alibaba.nacos:nacos-client"
}
